baseURL = "https://hughjonesd.github.io/suggestions"
languageCode = "en-us"
title = "Suggestions"
theme="hugo-book"
[params]
	mode="auto"
	useCDN=false
	subtitle = "A simple, human-readable diff and comment format"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

