baseURL = "https://hughjonesd.github.io/suggestions"
languageCode = "en-us"
title = "Suggestions"
theme="hugo-book"
[params]
	mode="auto"
	useCDN=false
	subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

